### ISSUE TITLE
Deploy script "failing" because of limited hosts

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/ansible-cira#102]
I've got a PR coming for this one, just wanted to document it quickly...

Looks like the deploy script, `./scripts/deploy.sh` is trying to kick off the plays for the `jenkins_slave` -- which isn't entirely configured for the deployment. 

E.g. I run `./scripts/deploy.sh` as the toad user, and it fails with:

```
PLAY [jenkins_slave] ***********************************************************

TASK [setup] *******************************************************************
fatal: [slave01]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).\r\n", "unreachable": true}
	to retry, use: --limit @/home/toad/toad/site.retry

PLAY RECAP *********************************************************************
jenkins_master             : ok=47   changed=2    unreachable=0    failed=0   
slave01                    : ok=0    changed=0    unreachable=1    failed=0   
```

But, if I changed the limited hosts, a la:

```
-ansible-playbook site.yml --limit jenkins_master,jenkins_slave -e use_openstack_deploy=false -e deploy_type='docker' -c docker
+ansible-playbook site.yml --limit jenkins_master -e use_openstack_deploy=false -e deploy_type='docker' -c docker
```

It succeeds.

**Comment by leifmadsen** [comment]
Soooooo,  this should have worked if the `deploy.sh` script was doing as it should have.

Part of the script is to set the `toad` use password to `toad` so that the values in the `hosts/minions` file allow Ansible to connect to the virthost. If that isn't working, then there is something else possibly wrong with the `deploy.sh` script.

**Comment by dougbtv** [comment]
Ok, was totally coming at this one from the wrong angle here!

Turns out the root cause was that my host was a CentOS 7 generic cloud, which denies password auth via ssh. So I'm brewing up a solution that creates the ssh keys and all that good stuff. PR coming up here any moment.
