### ISSUE TITLE
Add multiple node support for Jenkins slaves

### ISSUE THREAD

**Issue by leifmadsen** [redhat-nfvpe/ansible-cira#26]
Create a dictionary and permit ability to add multiple Jenkins slaves from a list. Add functionality to provide ability to delete Jenkins slave nodes using `absent` key term.

**Comment by redhat-nfvpe** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mWSe4AB7&#x2F;115-add-multiple-node-support-for-jenkins-slaves"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add multiple node support for Jenkins slaves</a>

**Comment by leifmadsen** [comment]
Resolved by @s1061123 via https://github.com/redhat-nfvpe/ansible-cira/commit/59662f43aafee5e3c94cd119e4ea43287e138362
