### ISSUE TITLE
Create simpler way to deal with SSH public/private keys

### ISSUE THREAD

**Issue by leifmadsen** [redhat-nfvpe/ansible-cira#31]
Build out a role, handler, or library (module) that makes it simpler to work with SSH keys between nodes. The purpose is to make it easier to create SSH public/private keys, and to distribute the public key amongst the various nodes that need to communicate with each other over SSH/SCP.

Public keys need to be added to authorized_keys file on the various nodes after key creation.

**Comment by redhat-nfvpe** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Fy0wyne6&#x2F;110-create-simpler-way-to-deal-with-ssh-public-private-keys"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Create simpler way to deal with SSH public&#x2F;private keys</a>

**Comment by leifmadsen** [comment]
While not perfect, I may consider this task done as I've at least placed all the SSH configuration stuff for Jenkins master/slave nodes into a single location, avoiding it being peppered all over a more complex file.
