### ISSUE TITLE
Support docker container instead of OpenStack/Vagrant

### ISSUE THREAD

**Issue by s1061123** [redhat-nfvpe/ansible-cira#48]
Currently (incl. proposed pull request by lmadsen), ansible-cira supports vagrant and OpenStack API to run jenkins_master/elasticsearch/kibana/logstash).

This ticket is used to add support docker as above.

Current design is as following:
- Image "centos:centos7" is used
- Use docker-compose command to launch docker containers
- After launch, ansible-playbook command is used to do provision (same design as vagrant/OpenStack)
- For some docker specific process, "cira_use_docker" variable is used

**Comment by leifmadsen** [comment]
Resolved via merge #49
