### ISSUE TITLE
Add ARA as dependency to installation

### ISSUE THREAD

**Issue by leifmadsen** [redhat-nfvpe/ansible-cira#53]
Currently when you install a new slave node and try to run the oooq-master-cira job, it fails to run because of the missing `ara` dependency.

**Comment by yrobla** [comment]
This is managed by requirements on nfv-job-configs... You would need to use https://gitlab.cee.redhat.com/nfvpe/nfv-job-configs/blob/master/requirements/cira-requirements.txt instead of default quickstart-extras-requirements, if you want to depend on ara.

**Comment by leifmadsen** [comment]
I think I found the problem. It's actually using `cira-requirements.txt` (or at least trying to) but not finding it. I see that the JJB is configuring the job to use the wrong path. I must have adjusted some stuff in the upstream repo, and didn't change it in the JJB templates. I'm going to fix that now.

**Comment by leifmadsen** [comment]
Fixed via #54
