### ISSUE TITLE
jenkins 2.32.2 not exist

### ISSUE THREAD

**Issue by zshi-redhat** [redhat-nfvpe/ansible-cira#89]
under vars/main.yml, jenkins_version is defined with 2.32.3, but it disappeared in below url
https://pkg.jenkins.io/redhat/

**Comment by leifmadsen** [comment]
It seems to deploy for me. I think the location that the packages are pulling from are different from that link? I remember getting confused once on the package version numbering once...

**Comment by zenghui-shi** [comment]
closing this issue as it never happened since reporting, seems like a mis-configuration problem;
please feel free to re-open it if anyone feels this is still an issue.
